version: "3.8"

services:
  sentiment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment-api
    ports:
      - "8000:80"        
    environment:
      - MODEL_OUTPUT_DIR=/app/output  
    restart: unless-stopped
